// Copyright 2021 Dasky (@daskygit)
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#define USB_VBUS_PIN B10
#define SPLIT_HAND_PIN B3

#define OLED_DISPLAY_128X64

#undef SOFT_SERIAL_PIN
#define SOFT_SERIAL_PIN A9
#define SERIAL_USART_SPEED 1200000
#define SERIAL_USART_TIMEOUT 10

#undef ENCODERS_PAD_A
#define ENCODERS_PAD_A { B15 }
#undef ENCODERS_PAD_B
#define ENCODERS_PAD_B { B14 }

#define PIMORONI_TRACKBALL_INTERVAL_MS 8
#define PIMORONI_TRACKBALL_SCALE 3
#define POINTING_DEVICE_ROTATION_90

#define I2C1_CLOCK_SPEED 400000
#define I2C1_DUTY_CYCLE FAST_DUTY_CYCLE_2

#undef RGBLIGHT_LIMIT_VAL
#define RGBLIGHT_LIMIT_VAL 200

#define SPLIT_TRANSACTION_IDS_KB MOUSE_SYNC
