MCU = RP2040

BOOTLOADER = rp2040

RGB_MATRIX_ENABLE = yes
WS2812_DRIVER = vendor
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
USER_NAME := dasky

SERIAL_DRIVER = vendor

ALLOW_WARNINGS = yes
PICO_INTRINSICS_ENABLED = no # ATM Unsupported by ChibiOS!

POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
POINTING_DEVICE_ENABLE = yes
